- hosts: localhost
  vars_prompt:
    - name: site_name
      prompt: "Enter the site name"
      private: no
  tasks:
    - ping: ~
    - fail: 
        msg: Need the site name before script can build it.
      when: site_name is undefined
    - name: Print Vars
      action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
      when: dump|default(false)|bool

     
    - name: Create CNAME for {{ site_name }} key {{ ddns_key_name }}
      nsupdate:
        key_name: "{{ ddns_key_name }}"
        key_secret: "{{ ddns_key_secret }}"
        server:  "{{ ddns_dns_server }}" 
        zone:  "{{ ddns_zone }}"  
        record: "{{ site_name }}.web-dev.skynet."
        type: "CNAME"
        value:  "{{ ddns_host_server }}"
        state: present 


  roles:
    - vhost
    - wordpress
